language: python
python:
  - "3.6"
cache: 
  pip: true
  directories:
  - node_modules  
install:
  - pip install ansible pylint boto3
before_script:
  - pushd ../
  - git clone https://github.com/willthames/ansible-lint.git
  - export PYTHONPATH=$PYTHONPATH:`pwd`/ansible-lint/lib
  - export PATH=$PATH:`pwd`/ansible-lint/bin
  - npm install -g cfn-lint
script:
  - popd
  - ansible-lint ansible/site.yml
  - cd ansible/inventories && pylint ec2.py
  - python -m unittest tests.test_ec2 -v
  - cd ../../aws/lambda/ && pylint console_login_check.py
  - python -m unittest tests.test_console_login_check -v
  - cd ../../aws/cloudformation && cfn-lint validate vpc.template.yaml
