language: python
python:
  - "3.6"
install:
  - pip install ansible pylint boto3
before_script:
  - pushd ../
  - git clone https://github.com/willthames/ansible-lint.git
  - export PYTHONPATH=$PYTHONPATH:`pwd`/ansible-lint/lib
  - export PATH=$PATH:`pwd`/ansible-lint/bin
script:
  - popd
  - ansible-lint ansible/site.yml
  - pylint ansible/inventories/ec2.py
  - cd ansible/inventories && python -m unittest tests.test_ec2 -v
  - cd ../../ && pylint aws/lambda/console_login_check.py -v
  - cd aws/lambda/ && python -m unittest tests.test_console_login_check.py -v
