language: python
python:
  - "3.6"
cache: 
  pip: true
install:
  - pip install ansible pylint boto3 cfn-lint ruamel.yaml
script:
  - pushd ./
  - cd aws/lambda/console_login_check && pylint console_login_check.py
  - python -m unittest tests.test_console_login_check -v
  - popd
  - cd  aws/cloudformation && cfn-lint vpc.template.yaml
