---
# roles/common/tasks/main.yml
- name: 時刻をJSTに変更
  file: src=/usr/share/zoneinfo/Asia/Tokyo path=/etc/localtime state=link force=yes
  changed_when: false

- name: 再起動後もJSTとなるように変更
  replace: dest=/etc/sysconfig/clock regexp='"UTC"' replace='"Asia/Tokyo"'
  changed_when: false

- name: EC2 メタデータ取得
  action: ec2_facts
  register: ec2_facts

- debug: var=ec2_facts

- name: EC2 タグ情報取得
  ec2_tag:
    region: '{{ ansible_ec2_placement_region }}'
    resource: '{{ ansible_ec2_instance_id }}'
    state: list
  register: ec2_tags

- name: ホスト名変更
  hostname: name='{{ ec2_tags.tags.Name }}-{{ env_name }}'
