AWSTemplateFormatVersion: '2010-09-09'
Description: 'Provisioning ALB'

Outputs:
    ALBID:
        Description: 'ALB ID'
        Value:
            !Ref ALB
        Export:
            Name: 'ALBID'
    ALBNAME:
        Description: 'ALB NAME'
        Value:
            !GetAtt ALB.LoadBalancerName
        Export:
            Name: 'ALBNAME'

Parameters:
    TagName:
        Description: 'For Name Tag'
        Type: 'String'
    Environment:
        AllowedValues:
            - dev
            - stg
            - prd
        Default: 'dev'
        Description: 'Environment (e.g. dev, stg, prd)'
        Type: 'String'
    MyIp:
        Description: 'My source ip adress. xxx.xxx.xxx.xxx/32'
        Type: 'String'
    VPCID:
        Description: 'which dou you use VPC?'
        Type: 'AWS::EC2::VPC::Id'

Conditions:
    CreateProdResources: !Equals [ !Ref Environment, prd ]

Mappings:
    S3Config:
        us-east-1:
            BucketPrincipal: '127311923021'
        us-east-2:
            BucketPrincipal: '033677994240'
        us-west-1:
            BucketPrincipal: '027434742980'
        us-west-2:
            BucketPrincipal: '797873946194'
        ca-central-1:
            BucketPrincipal: '985666609251'
        eu-west-1:
            BucketPrincipal: '156460612806'
        eu-central-1:
            BucketPrincipal: '054676820928'
        eu-west-2:
            BucketPrincipal: '652711504416'
        ap-northeast-1:
            BucketPrincipal: '582318560864'
        ap-northeast-2:
            BucketPrincipal: '600734575887'
        ap-southeast-1:
            BucketPrincipal: '114774131450'
        ap-southeast-2:
            BucketPrincipal: '783225319266'
        ap-south-1:
            BucketPrincipal: '718504428378'
        sa-east-1:
            BucketPrincipal: '507241528517'
        us-gov-west-1:
            BucketPrincipal: '048591011584'
        cn-north-1:
            BucketPrincipal: '638102146993'

Resources:
    LogBucket:
        Type: 'AWS::S3::Bucket'
        Condition: CreateProdResources
        Properties:
            BucketName: 'yokobot-alb-logs'
            LifecycleConfiguration:
                Rules:
                - Id: expire180
                  Status: Enabled
                  ExpirationInDays: '180'
    BucketPolicyELBLogBucket:
        Type: 'AWS::S3::BucketPolicy'
        Condition: CreateProdResources
        Properties:
            Bucket: !Ref LogBucket
            PolicyDocument:
                Id: 'Allow-Put-ELB-logs'
                Version: '2012-10-17'
                Statement:
                    - Sid: 'Stmt1429136633762'
                      Action:
                          - 's3:PutObject'
                      Effect: 'Allow'
                      Resource:
                          Fn::Join:
                              - ''
                              - - 'arn:aws:s3:::'
                                - !Ref LogBucket
                                - '/AWSLogs/'
                                - !Ref AWS::AccountId
                                - '/*'
                      Principal:
                          AWS: !FindInMap [ S3Config, Ref: 'AWS::Region', BucketPrincipal ]
    SgALB:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            GroupDescription: 'Security Group For ALB'
            VpcId: !Ref VPCID
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: '80'
              ToPort: '80'
              CidrIp:
                  !If [ 'CreateProdResources', '0.0.0.0/0', !Ref MyIp ]
            Tags:
                - Key: 'Name'
                  Value: !Join
                      - '-'
                      - - !Ref TagName
                        - 'alb'
                        - 'sg'
                        - !Ref Environment
    ALB:
        Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
        Properties:
            Scheme: 'internet-facing'
            Name:
                !Join
                    - '-'
                    - - !Ref TagName
                      - 'alb'
                      - !Ref Environment
            LoadBalancerAttributes:
                !If
                    - CreateProdResources
                    - - Key: idle_timeout.timeout_seconds
                        Value: '60'
                      - Key: access_logs.s3.enabled
                        Value: 'true'
                      - Key: deletion_protection.enabled
                        Value: 'true'
                      - Key: access_logs.s3.bucket
                        Value: !Ref LogBucket
                    - !Ref 'AWS::NoValue'
            SecurityGroups:
            - !Ref SgALB
            Subnets:
            - !ImportValue SubnetPublicAID
            - !ImportValue SubnetPublicCID
            Tags:
                - Key: 'Name'
                  Value: !Join
                     - '-'
                     - - !Ref TagName
                       - 'alb'
                       - !Ref Environment
