version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "auto-start-stop"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yokobot"
s3_prefix = "auto-start-stop"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

